# Start from Alpine
FROM alpine

# Set the working directory to /app
WORKDIR /app

# Copy the build into the container at /app
ADD ./bin/prime-fast/prime-fast /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run prime when the container launches
ENTRYPOINT /app/prime-fast