
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: prime
spec:
  # 1 Pod should exist by default.
  replicas: 1
  # Determines how to find the deployment when updating it
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: prime
        version: prime-v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: version
                operator: In
                values:
                - prime-v1
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: prime 
        # Run this image
        image: docker.io/razakal/prime:prime-v1
        # Do not reuse cached images
        imagePullPolicy: Always
        ports:
          # Open port 8080 TCP on the containers
        - containerPort: 8080
        # Cpu and Memory requirements
        resources:
          requests:
            cpu: 0.2
            memory: 50Mi
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: prime
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: prime
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prime
spec:
  backend:
    serviceName: prime
    servicePort: 8080
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  # Unique key of the Autoscaler instance
  name: prime  
spec:
  # Maximum amount of replicas that it is allowed to create
  maxReplicas: 10
  # Average CPU load to remain over all pods
  targetCPUUtilizationPercentage: 50
  # Reference to the deployment that has to be autoscaled
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prime      